# Generated by Django 5.2.4 on 2025-07-08 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('monitoring', '모니터링 AI 에이전트'), ('prediction', '예측 AI 에이전트'), ('control', '자율제어 AI 에이전트'), ('orchestration', '오케스트레이션 AI 에이전트')], max_length=100, unique=True)),
                ('description', models.TextField()),
                ('template_config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('interface_type', models.CharField(choices=[('sensor', '센서'), ('scada', 'SCADA'), ('api', 'API'), ('database', '데이터베이스'), ('mqtt', 'MQTT')], max_length=20)),
                ('endpoint', models.CharField(max_length=500)),
                ('authentication', models.JSONField(default=dict)),
                ('configuration', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google'), ('local', 'Local Model')], max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('endpoint', models.URLField(blank=True)),
                ('performance_score', models.FloatField(default=0.0)),
                ('cost_per_token', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('max_tokens', models.IntegerField(default=4096)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('regulation_type', models.CharField(choices=[('safety', '안전 규정'), ('legal', '법적 규정'), ('policy', '내부 정책'), ('standard', '표준')], max_length=20)),
                ('content', models.TextField()),
                ('version', models.CharField(max_length=50)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('configuration', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', '초안'), ('configured', '설정완료'), ('testing', '테스트중'), ('active', '활성'), ('inactive', '비활성'), ('error', '오류')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('agent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agiApp.agenttype')),
                ('llm_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agiApp.llmmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', '대기중'), ('running', '실행중'), ('completed', '완료'), ('failed', '실패'), ('cancelled', '취소')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agiApp.agent')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('debug', 'DEBUG'), ('info', 'INFO'), ('warning', 'WARNING'), ('error', 'ERROR'), ('critical', 'CRITICAL')], max_length=20)),
                ('module', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agiApp.agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', '정보'), ('warning', '경고'), ('error', '오류'), ('success', '성공')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
