# Generated by Django 5.2.4 on 2025-07-29 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agiApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='agent_type',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='llm_model',
        ),
        migrations.RemoveField(
            model_name='systemlog',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='agenttask',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='agenttask',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='ExternalInterface',
        ),
        migrations.DeleteModel(
            name='Regulation',
        ),
        migrations.RemoveField(
            model_name='systemlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='systemnotification',
            name='user',
        ),
        migrations.DeleteModel(
            name='AgentType',
        ),
        migrations.DeleteModel(
            name='LLMModel',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='AgentTask',
        ),
        migrations.DeleteModel(
            name='SystemLog',
        ),
        migrations.DeleteModel(
            name='SystemNotification',
        ),
    ]
