# Generated by Django 5.2.4 on 2025-08-25 06:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agiApp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='user_1234', max_length=100)),
                ('action_type', models.CharField(choices=[('agent_create', '에이전트 생성'), ('agent_delete', '에이전트 삭제'), ('tool_register', '도구 등록'), ('tool_delete', '도구 삭제'), ('chat_query', '자연어 질의'), ('session_create', '채팅 세션 생성'), ('session_delete', '채팅 세션 삭제')], max_length=20)),
                ('level', models.CharField(choices=[('INFO', '정보'), ('WARNING', '경고'), ('ERROR', '오류'), ('DEBUG', '디버그')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', 'action_type'], name='agiApp_user_user_id_2c6752_idx'), models.Index(fields=['timestamp'], name='agiApp_user_timesta_9fd9ca_idx'), models.Index(fields=['level'], name='agiApp_user_level_898cdc_idx')],
            },
        ),
    ]
