# Generated by Django 5.2.4 on 2025-08-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agiApp', '0004_useractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='session_user_id',
            field=models.CharField(blank=True, help_text='user_1234_task_숫자 형식', max_length=100),
        ),
    ]
