# Generated by Django 5.2.4 on 2025-08-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agiApp', '0005_chatmessage_session_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
