# Generated by Django 5.2.4 on 2025-10-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agiApp', '0006_alter_chatsession_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='action_type',
            field=models.CharField(choices=[('agent_create', '에이전트 생성'), ('agent_delete', '에이전트 삭제'), ('tool_register', '도구 등록'), ('tool_delete', '도구 삭제'), ('chat_query', '자연어 질의'), ('session_create', '채팅 세션 생성'), ('session_delete', '채팅 세션 삭제'), ('session_rename', '채팅 세션 이름 변경'), ('orchestrate_error', '에이전트 연결 실패'), ('system_error', '시스템 오류')], max_length=20),
        ),
    ]
