# Generated by Django 5.2.4 on 2025-11-05 17:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agiApp', '0007_alter_useractivitylog_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrchestrateStepUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_user_id', models.CharField(help_text='user_1234_task_숫자 형식', max_length=100)),
                ('agent_name', models.CharField(blank=True, help_text='담당 에이전트 이름', max_length=100)),
                ('step_name', models.CharField(help_text='단계 이름', max_length=100)),
                ('content', models.TextField(help_text='단계별 업데이트 내용 (Markdown)')),
                ('status', models.CharField(default='completed', help_text='completed, in_progress, error, running', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='진행률 (0-100)')),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sequence', models.IntegerField(default=0, help_text='업데이트 순서')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_updates', to='agiApp.chatmessage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_updates', to='agiApp.chatsession')),
            ],
            options={
                'ordering': ['session', 'sequence', 'timestamp'],
                'indexes': [models.Index(fields=['session', 'sequence'], name='agiApp_orch_session_675187_idx'), models.Index(fields=['session_user_id'], name='agiApp_orch_session_7eac9b_idx')],
            },
        ),
    ]
