# Generated by Django 5.2.4 on 2025-07-08 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='제어 시스템 이름')),
                ('system_type', models.CharField(choices=[('plc', 'PLC'), ('scada', 'SCADA'), ('dcs', 'DCS'), ('api', 'API'), ('mqtt', 'MQTT')], max_length=20, verbose_name='시스템 유형')),
                ('description', models.TextField(verbose_name='시스템 설명')),
                ('endpoint', models.CharField(max_length=500, verbose_name='엔드포인트')),
                ('authentication', models.JSONField(default=dict, verbose_name='인증 정보')),
                ('configuration', models.JSONField(default=dict, verbose_name='설정')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '제어 시스템',
                'verbose_name_plural': '제어 시스템',
            },
        ),
        migrations.CreateModel(
            name='SafetyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='규칙 이름')),
                ('rule_type', models.CharField(choices=[('threshold', '임계값'), ('sequence', '순서'), ('condition', '조건'), ('interlock', '인터록')], max_length=20, verbose_name='규칙 유형')),
                ('description', models.TextField(verbose_name='규칙 설명')),
                ('conditions', models.JSONField(default=dict, verbose_name='조건')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '안전 규칙',
                'verbose_name_plural': '안전 규칙',
            },
        ),
        migrations.CreateModel(
            name='ControlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='시간')),
                ('log_type', models.CharField(choices=[('command', '명령'), ('action', '액션'), ('alarm', '알람'), ('safety', '안전')], max_length=20, verbose_name='로그 유형')),
                ('message', models.TextField(verbose_name='메시지')),
                ('data', models.JSONField(default=dict, verbose_name='데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('control_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_agent.controlsystem', verbose_name='제어 시스템')),
            ],
            options={
                'verbose_name': '제어 로그',
                'verbose_name_plural': '제어 로그',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ControlCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.CharField(max_length=100, unique=True, verbose_name='명령 ID')),
                ('command_type', models.CharField(choices=[('start', '시작'), ('stop', '정지'), ('adjust', '조정'), ('reset', '리셋'), ('emergency_stop', '비상 정지')], max_length=20, verbose_name='명령 유형')),
                ('parameters', models.JSONField(default=dict, verbose_name='명령 파라미터')),
                ('priority', models.IntegerField(default=1, verbose_name='우선순위')),
                ('approval_required', models.BooleanField(default=True, verbose_name='승인 필요')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('approved', '승인됨'), ('executing', '실행중'), ('completed', '완료'), ('failed', '실패'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='상태')),
                ('safety_check_passed', models.BooleanField(default=False, verbose_name='안전 검사 통과')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='실행 시간')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시간')),
                ('result', models.JSONField(default=dict, verbose_name='실행 결과')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_commands', to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('control_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_agent.controlsystem', verbose_name='제어 시스템')),
            ],
            options={
                'verbose_name': '제어 명령',
                'verbose_name_plural': '제어 명령',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ControlAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='액션 이름')),
                ('action_type', models.CharField(choices=[('manual', '수동'), ('automatic', '자동'), ('emergency', '비상')], max_length=20, verbose_name='액션 유형')),
                ('description', models.TextField(verbose_name='액션 설명')),
                ('action_config', models.JSONField(default=dict, verbose_name='액션 설정')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_agent.controlsystem', verbose_name='제어 시스템')),
            ],
            options={
                'verbose_name': '제어 액션',
                'verbose_name_plural': '제어 액션',
            },
        ),
    ]
