# Generated by Django 5.2.4 on 2025-07-08 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=100, verbose_name='센서 ID')),
                ('sensor_name', models.CharField(max_length=200, verbose_name='센서 이름')),
                ('location', models.CharField(max_length=200, verbose_name='위치')),
                ('timestamp', models.DateTimeField(verbose_name='측정 시간')),
                ('value', models.FloatField(verbose_name='측정값')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='단위')),
                ('anomaly_type', models.CharField(choices=[('normal', '정상'), ('warning', '경고'), ('critical', '심각'), ('unknown', '알 수 없음')], default='normal', max_length=20, verbose_name='이상 유형')),
                ('anomaly_score', models.FloatField(default=0.0, verbose_name='이상 점수')),
                ('threshold_min', models.FloatField(blank=True, null=True, verbose_name='최소 임계값')),
                ('threshold_max', models.FloatField(blank=True, null=True, verbose_name='최대 임계값')),
                ('explanation', models.TextField(blank=True, verbose_name='이상 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '모니터링 데이터',
                'verbose_name_plural': '모니터링 데이터',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='대시보드 이름')),
                ('description', models.TextField(verbose_name='설명')),
                ('layout_config', models.JSONField(default=dict, verbose_name='레이아웃 설정')),
                ('sensor_groups', models.JSONField(default=list, verbose_name='센서 그룹')),
                ('refresh_interval', models.IntegerField(default=5, verbose_name='새로고침 간격(초)')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본 대시보드')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '모니터링 대시보드',
                'verbose_name_plural': '모니터링 대시보드',
            },
        ),
        migrations.CreateModel(
            name='AnomalyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='알림 제목')),
                ('description', models.TextField(verbose_name='알림 내용')),
                ('priority', models.CharField(choices=[('low', '낮음'), ('medium', '보통'), ('high', '높음'), ('critical', '심각')], default='medium', max_length=20, verbose_name='우선순위')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='확인됨')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='확인 시간')),
                ('recommended_actions', models.JSONField(default=list, verbose_name='권장 조치')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='확인자')),
                ('monitoring_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring_agent.monitoringdata')),
            ],
            options={
                'verbose_name': '이상 알림',
                'verbose_name_plural': '이상 알림',
                'ordering': ['-created_at'],
            },
        ),
    ]
